version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "7001:3005"
    environment:
      - DATABASE_URL_MAIN=postgresql://postgres:1Nihidupku!@103.196.155.0:5433/db_occ?schema=public
      - DATABASE_URL_SECONDARY=mysql://unikas:5ky50p4y123!.@147.139.137.204:3306/parkingasservices
      - NODE_ENV=production
      - JWT_SECRET=158243e2-ccc0-4798-a944-2a5b0d1c90f3
      - SIGNATURE_SECRET=c719f771-69ce-4945-9895-1759fb49df87
      - URL_LOGIN=https://devtest08.skyparking.online
      - PLATE_RECOGNIZER_TOKEN=2ee83fb34e74d1bd32772ac11129862e8f8161e1
      - TOKEN_FONTEE=YJF6FhPtZJVuQafteWFX

    restart: always

    volumes:
      - ./uploads:/app/uploads
